version: '3.1'

services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    volumes:
     - ./src:/home/com_staffvalidator
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: devdbpassword

  joomladb:
    image: mysql:5.6
    restart: always
    ports:
      - 3030:3306
    environment:
      MYSQL_ROOT_PASSWORD: devdbpassword
